---
title: "Informative Title Name"
author: "GROUP NUMBER: ADD YOUR NAMES HERE"
date: November 24, 2022
subtitle: STA304 - Assignment 2
output:
  pdf_document: default
---

```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(openintro)
library(tidyverse)
```


# 1 Read in the sample data.

```{r, include = FALSE}

survey_data <- read_csv("sample_ces-phone.csv")

```

```{r, include = FALSE}

survey_data <- 
  survey_data %>% 
  mutate(age = 2019-q2,
         vote_liberal = ifelse(q11==1, 1, 0)) %>% 
  select(age, vote_liberal)

```

# 2 Model the sample outcome of interest.


```{r, include=FALSE}

model <- lm(vote_liberal ~ age, data=survey_data)

```

# 3 Read in the census data.

Here you can load in the census data. 

```{r, include = FALSE}
census_data <- read_csv("census_data-gss.csv")

census_data <- census_data %>% 
  mutate(age=round(age)) %>% 
  select(age)
```


# 4 Apply the model to the census counts.


```{r, include=FALSE}

# Here I will perform the post-stratification calculation
census_data_counts <- census_data %>% 
  group_by(age) %>% 
  summarise(n=n())

census_data_counts$estimate <-
  model %>%
  predict(newdata = census_data_counts)

census_data_counts %>% 
  mutate(liberal_predict_prop = estimate*n) %>%
  summarise(liberal_predict = sum(liberal_predict_prop)/sum(n))

```

